# Generated by Django 3.1.5 on 2021-04-25 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 14, 47, 9, 167445)),
        ),
    ]
